### ISSUE TITLE
Можно ли добавить еще и другие версии ep ?

### ISSUE THREAD

**Issue by aleks-spv** [Scorpikor/pynod-mirror-tool#1]
Привет!
Можно ли добавить еще и другие версии ep 9, 10?

**Comment by Scorpikor** [comment]
Привет, да, я уже добавил эти версии, обновитесь до последней версии. Чтоб скрипт начал скачивать базы этих версий, надо в конфиге (файл nod32ms.conf) выставить следующие значения
versionep9   = 1
versionep10  = 1
Так же, зеркало, с которого вы скачиваете базы, должно иметь базы для этих версий.

**Comment by Scorpikor** [comment]
В конфиг скрипта добавлены актуальные версии антивируса для обновления
